apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: dev-getting-started
          image: yourdockerhubuser/getting-started:dev
          env:
            - name: ENV
              value: "development"


